# Generated by Django 3.0.4 on 2020-04-21 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitordata',
            name='cookie',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='visitordata',
            name='package_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
