# Generated by Django 3.0.4 on 2020-05-02 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200421_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitordata',
            name='meals_per_day',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
