# Generated by Django 3.0.4 on 2020-05-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_visitordata_meals_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitordata',
            name='cookie',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
