# Generated by Django 3.0.4 on 2020-05-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200503_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitordata',
            old_name='package_count',
            new_name='packages_count',
        ),
    ]
