# Generated by Django 3.0.4 on 2020-05-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200503_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitordata',
            old_name='package_weight',
            new_name='package_volume',
        ),
        migrations.RenameField(
            model_name='visitordata',
            old_name='weight_per_meal',
            new_name='wb_per_meal',
        ),
    ]
