# Generated by Django 3.0.4 on 2020-05-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_inviteentry_is_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteentry',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
