# Generated by Django 3.0.4 on 2020-05-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20200504_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inviteentry',
            options={'ordering': ['date', '-is_validated']},
        ),
    ]
