# Generated by Django 3.0.4 on 2020-05-17 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20200504_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=128, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=256)),
                ('likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dislikes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['likes', 'date'],
            },
        ),
        migrations.CreateModel(
            name='RatingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('L', 'Like'), ('D', 'Dislike')], max_length=1)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Comment')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.VisitorData')),
            ],
        ),
    ]
